---
- name: spc
  become: yes
  hosts: localhost
  vars:
  tasks:
    - name: copy service to sudo touch /etc/systemd/system/spc.service
      ansible.builtin.copy:   
        src: spc.service
        dest: /etc/systemd/system/spc.service
        mode: '664'
    - name: enable and state service
      ansible.builtin.systemd:
        name: spc.service
        enabled: true
        daemon_reload: true
        state: started  
