---
pool: 'Default'
trigger: 
  -  main
stages:
  - stage: build_spc
    jobs:
      - job: ansible_installed vm
        steps:
          - script: terraform apply 
      - job: spc
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'Path'
              jdkVersionOption: '1.17'
              jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
              mavenVersionOption: 'Path' 
              mavenDirectory: /opt/apache-maven-3.6.3
              mavenAuthenticateFeed: false 
              effectivePomSkip: false
              sonarQubeRunAnalysis: false 
          - task: PublishBuildArtifacts@1
            inputs: 
              PathtoPublish: '$(Build.Repository.LocalPath)/target/spring-petclinic-2.7.3.jar'
              ArtifactName: 'spc'
  - stage: download_spc
    dependsOn: build_spc
    jobs:
      - job: download_spc_Artifacts
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: spc
              targetPath: /tmp/
          - script: ansible-playbook -i host ansible1.yaml

