---
pool: 'Default'
parameters:
  - name: s3bucket
    type: string
    default: spc1811
    values:
      - spc1811
trigger: 
  -  main
jobs:
  - job: spc
    steps:
      - task: Maven@3
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'Path'
          jdkVersionOption: '1.17'
          jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
          mavenVersionOption: 'Path' 
          mavenDirectory: /opt/apache-maven-3.6.3
          mavenAuthenticateFeed: false 
          effectivePomSkip: false
          sonarQubeRunAnalysis: false 
      - script: aws s3 cp  '$(Build.Repository.LocalPath)/target/spring-petclinic-2.7.3.jar' s3://${{parameters.s3bucket}}/ --acl public-read
      - script: ansible-playbook -i host ansible.yml
      