---
- name: install java17
  become: yes
  hosts: localhost
  tasks:
  - name: update packages
    ansible.builtin.apt:
      update_cache: yes
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: install java17
    ansible.builtin.package:
      name: openjdk-17-jdk
      state: present